name: songlib
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  drift: ^2.5.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  file_local_storage_inspector: ^0.3.1
  flutter_svg: ^2.0.7
  get_it: ^7.2.0
  http: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  niddler_dart: ^1.6.0
  path: ^1.8.2
  path_provider: ^2.0.12
  preferences_local_storage_inspector: ^0.3.1
  provider: ^6.0.5
  retrofit: ^4.0.1
  scroll_when_needed: ^3.0.1
  secure_storage_local_storage_inspector: ^0.6.0
  shared_preferences: ^2.0.17
  sqlite3_flutter_libs: ^0.5.12
  universal_platform: ^1.0.0+1
  upgrader: ^8.1.0
  firebase_analytics: ^10.4.4

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  license_generator: ^2.0.0
  icapps_translations: ^11.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0
  mockito: ^5.3.2
  model_generator: ^6.0.2
  retrofit_generator: ^7.0.8

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/sound/
  fonts:
    - family: Trebuchet
      fonts:
        - asset: assets/fonts/Trebuchet-MS.ttf
